name: clojureaction
description: GitHub Action to build Clojure projects
author: Ambrose Bonnaire-Sergeant
'on':
  workflow_call: {}
inputs:
  edn:
    description: |-
      An edn map with the following keys:

      # YAML Example:

        - uses: frenchy64/clojureaction@release
          with:
            edn: |-
              {:commands
               (cons
                "clj-kondo"
                (for
                 [java [11 21] clojure ["1.11" "1.12"]]
                 {:setup-java {:java-version java},
                  :name (format "Test (Clojure %s, Java %s)" clojure java),
                  :command (format "lein with-profile +%s test" clojure)})),
               :download-deps "lein with-profile +test,+clj-kondo deps",
               :target-duration [5 :minutes],
               :java 21}

      # Supported keys:
      - :test  A command to run Clojure tests
        Example: "lein test"
        Default: none
      - :download-deps  A command to download all Clojure dependencies.
        Example: "lein deps"
        Default: none
      - :lint  A command to lint Clojure sources.
        Example: "clj-kondo"
        Default: none
      - :setup-clojure
      - :java
      - :target-duration  Target duration for entire build.
        Example: [5 :minutes]
      - :ineffective-cache-detection  If true, fail the build if dependencies are still
                                      downloaded on a cache-hit.
        Default: true
jobs:
- setup:
    runs-on: ubuntu-latest
    steps:
    - uses: DeLaGuardo/setup-clojure@13.0
      with:
        bb: 1.12.195
    - uses: actions/checkout@v4
      with:
        repository: frenchy64/clojureaction
        ref: |
          c17d5c9b6e47587cff7ca07e39c84122635f1e8e
        path: |
          ../clojureaction-c17d5c9b6e47587cff7ca07e39c84122635f1e8e
    - working-directory: |
        ../clojureaction-c17d5c9b6e47587cff7ca07e39c84122635f1e8e
      run: ./src/clojureaction/eval_config.clj '${{ inputs.edn }}'
- run:
    needs: setup
